import Head from "next/head";

export default function Admin() {
    return (
        <div>
            <Head>
                <title>Create Next App Francis </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <h1> update fun </h1>
        </div>
    )
}